version: "3.5"
services:
  brain:
    image: "brain.web3signer.dnp.dappnode.eth:0.1.0"
    build:
      context: brain
    depends_on:
      web3signer:
        condition: service_healthy
    environment:
      - LOG_LEVEL=debug
    restart: unless-stopped
    volumes:
      - "brain_data:/app/data"
  web3signer:
    image: "web3signer.web3signer.dnp.dappnode.eth:0.1.0"
    healthcheck:
      test: >-
        curl -H 'Host: web3signer.web3signer-prater.dappnode'
        http://localhost:9000/healthcheck
      interval: 5s
      timeout: 5s
      retries: 20
    depends_on:
      postgres:
        condition: service_started
    build:
      context: web3signer
      dockerfile: Dockerfile
      args:
        UPSTREAM_VERSION: 23.3.1
    environment:
      LOG_TYPE: INFO
      EXTRA_OPTS: ""
    volumes:
      - "web3signer_data:/data"
    restart: unless-stopped
  postgres:
    image: "postgres.web3signer.dnp.dappnode.eth:0.1.0"
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: postgres
      dockerfile: Dockerfile
      args:
        UPSTREAM_VERSION: 23.3.1
    user: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "postgres_migrations:/docker-entrypoint-initdb.d"
    restart: unless-stopped
volumes:
  brain_data: {}
  web3signer_data: {}
  postgres_data: {}
  postgres_migrations: {}
